### ISSUE TITLE
Gradient in IntensityNllCriterionLayer

### ISSUE THREAD

**Issue by zhougt** [dunan/NeuralPointProcess#1]
I got a question regarding the gradient computation of IntensityNllCriterionLayer. I found the gradient of the negative log likelihood -log(f(t)) w.r.t. w_scalar is like:
`-delta_t + grad / w_scalar + exp(cur_state) * delta_t / w_scalar`
where
`cur_state = v' * h + w_scalar * delta_t + b` (i.e., the variable "cur_state" in line 78);
`grad = ( exp(v' * h + b) - exp(cur_state) ) / w_scalar` (i.e., the variable "grad" in line 39).

If my derive is correct, then the line 77 of intensity_nll_criterion_layer.cpp should be
`dw += grad.Sum() / w_scalar`
instead of
`dw -= grad.Sum() / w_scalar`

Please let me know if there is anything I missed. Thank you!

**Comment by dunan** [comment]
Hi zhougt, we descend on the negative gradient direction to minimize the negative loglikelihood.

**Comment by zhougt** [comment]
Hi Nan,

Thank you for the reply.

Yep, I figured out that the correct usage of the axpy function. The grad should be:
"grad = ( exp(cur_state) - exp(v' * h + b) ) / w_scalar"
There is no problem with the gradient computation. Sorry for bothering :-)
